version: '2'
services:
  db:
    image: postgres
  web:
    image: django:v1.1
    build: 
        context: .
        dockerfile: Dockerfile.python
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  rails:
    build:
        context: .
        dockerfile: Dockerfile.rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
